CREATE TABLE CESAR.ESTUDANTE (
	id NUMERIC NOT NULL,
	nome VARCHAR2(200) NOT NULL,
	data_nascimento DATE NOT NULL,
	nr_matricula NUMERIC(10) UNIQUE NOT NULL,
	ativo CHAR(1),
	PRIMARY KEY (id)	
);

CREATE SEQUENCE CESAR.SEQ_ESTUDANTE
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

INSERT INTO ESTUDANTE (ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES (SEQ_ESTUDANTE.nextval, 'Vegeta', TO_DATE('7/11/1946','dd-mm-yyyy'),'1111111111','S');

INSERT INTO ESTUDANTE (ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES (SEQ_ESTUDANTE.nextval, 'Goku', TO_DATE('16/04/1946','dd-mm-yyyy'),'2222222222','S');

INSERT INTO ESTUDANTE (ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES (SEQ_ESTUDANTE.nextval, 'Sasuke', TO_DATE('23/07/1946','dd-mm-yyyy'),'3333333333','S');

INSERT INTO ESTUDANTE (ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES (SEQ_ESTUDANTE.nextval, 'Naruto', TO_DATE('10/10/1946','dd-mm-yyyy'),'4444444444','S');

INSERT INTO ESTUDANTE (ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES (SEQ_ESTUDANTE.nextval, 'Ikki de Fenix', TO_DATE('7/11/1946','dd-mm-yyyy'),'5555555555','S');

INSERT INTO ESTUDANTE (ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES (SEQ_ESTUDANTE.nextval, 'Dohko de Libra', TO_DATE('7/11/1946','dd-mm-yyyy'),'6666666666','S');

INSERT INTO ESTUDANTE (ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES (SEQ_ESTUDANTE.nextval, 'Jack Bauer', TO_DATE('7/11/1946','dd-mm-yyyy'),'7777777777','N');

INSERT INTO ESTUDANTE (ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES (SEQ_ESTUDANTE.nextval, 'Dr. House', TO_DATE('7/11/1946','dd-mm-yyyy'),'8888888888','N');

INSERT INTO ESTUDANTE (ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES (SEQ_ESTUDANTE.nextval, 'Kenshin', TO_DATE('7/11/1946','dd-mm-yyyy'),'9999999999','N');

INSERT INTO ESTUDANTE (ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES (SEQ_ESTUDANTE.nextval, 'Inuyasha', TO_DATE('3/10/2009','dd-mm-yyyy'),'1000000000','N');

SELECT * FROM ESTUDANTE;